modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "decobeacon"
version = "${version}"
displayName = "Deco Beacon"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.decobeacon]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.decobeacon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.decobeacon]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "BOTH"